version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  uaserver:
    build: ./uamock
    ports:
      - "4840:4840"
    volumes:
      - ./uamock/src:/app/src

volumes:
  mongo:
