query GetCategories {
  categories {
    id
    name
    color
    rank
  }
}

query GetCategoryById($id: String!) {
  category(categoryId: $id) {
    name
    color
  }
}

mutation AddNewCategory($newCategory: AddCategoryInput!, $ranking: RankingInput!) {
  addCategory(newCategory: $newCategory, ranking: $ranking) {
    id
  }
}

mutation UpdateCategory($updatedCategory: UpdateCategoryInput!, $ranking: RankingInput) {
  updateCategory(updatedCategory: $updatedCategory, ranking: $ranking) {
    id
  }
}
